eddycharly/terraform-provider-kops

- docs/Cluster.generated.md
- docs/RollingUpdateOptions.generated.md
- docs/ValidateOptions.generated.md
- hack/gen-structures/main.go
- pkg/api/Cluster.go
- pkg/api/Cluster_sync.go
- pkg/api/RollingUpdateOptions.go
- pkg/api/ValidateOptions.go
- pkg/schemas/Cluster.generated.go
- pkg/schemas/RollingUpdateOptions.generated.go
- pkg/schemas/ValidateOptions.generated.go
- pkg/structures/Cluster.generated.go
- pkg/structures/RollingUpdateOptions.generated.go
- pkg/structures/ValidateOptions.generated.go
This PR add rolling update and validate cluster options.
Fixes #14
> feat: add rolling update and validate options

- .github/workflows/release.yaml
- .goreleaser.yaml
- README.md
- docs/AwsConfig.generated.md
- docs/ProviderConfig.generated.md
- examples/aws-profile/provider.tf
- hack/gen-structures/main.go
- pkg/api/AwsConfig.go
- pkg/api/ProviderConfig.go
- pkg/config/config.go
- pkg/provider/provider.go
- pkg/schemas/AwsConfig.generated.go
- pkg/schemas/ProviderConfig.generated.go
- pkg/structures/AwsConfig.generated.go
- pkg/structures/ProviderConfig.generated.go
This PR adds provider config generation.
> feat: add provider config generation

- go.mod
- hack/gen-tf-code/main.go
- pkg/api/AwsConfig.go
- pkg/config/config.go
- pkg/schemas/AwsAssumeRole.generated.go
- pkg/structures/AwsAssumeRole.generated.go
- pkg/structures/AwsConfig.generated.go
This PR adds assume role support.
> feat: add assume role support

- Makefile
- docs/data-sources/cluster.md
- docs/data-sources/instance_group.md
- docs/data-sources/kube_config.md
- docs/provider-config/provider.md
- docs/resources/cluster.md
- docs/resources/instance_group.md
- hack/gen-tf-code/data-cluster-header.md
- hack/gen-tf-code/data-instance-group-header.md
- hack/gen-tf-code/data-kube-config-header.md
- hack/gen-tf-code/docs.go
- hack/gen-tf-code/main.go
- hack/gen-tf-code/resource-cluster-footer.md
- hack/gen-tf-code/resource-cluster-header.md
- hack/gen-tf-code/resource-instance-group-footer.md
- hack/gen-tf-code/resource-instance-group-header.md
This PR improves generated docs by providing example usage and an import section when relevant.
> feat: improve docs

- pkg/api/resources/Cluster.go
- pkg/api/resources/ClusterUpdater.go
- pkg/resources/ClusterUpdater.go
This PR fixes cluster updater inconsistency and add missing apply cluster command code
> fix: cluster updater inconsistency + apply cluster command

- Makefile
- README.md
- docs/index.md
- docs/resources/cluster_updater.md
- hack/gen-tf-code/main.go
- hack/gen-tf-code/resource-cluster-updater-header.md
- pkg/api/resources/ClusterUpdater.go
- pkg/api/resources/RollingUpdateOptions.go
- pkg/api/utils/cluster_apply.go
- pkg/api/utils/cluster_rolling_update.go
- pkg/schemas/resources/Resource_ClusterUpdater.generated.go
- pkg/schemas/resources/Resource_RollingUpdateOptions.generated.go
- pkg/schemas/utils/Resource_RollingUpdateOptions.generated.go
This PR improves cluster updater resource.
> feat: improve cluster updater resource

- docs/data-sources/kube_config.md
- docs/resources/cluster.md
- docs/resources/cluster_updater.md
- docs/resources/instance_group.md
- hack/gen-tf-code/main.go
- pkg/schemas/resources/Resource_Cluster.generated.go
- pkg/schemas/resources/Resource_ClusterUpdater.generated.go
- pkg/schemas/resources/Resource_InstanceGroup.generated.go
- pkg/schemas/zzz_utils.go
This PR adds support for immutable fields
> feat: add support for immutable fields

- pkg/api/resources/InstanceGroup.go
- pkg/api/utils/instance_group_delete.go
- pkg/resources/InstanceGroup.go
This PR fixes instance group deletion.
> fix: delete instance group

- pkg/resources/Cluster.go
> fix: cluster import

- pkg/config/config.go
- pkg/datasources/Cluster.go
- pkg/datasources/ClusterStatus.go
- pkg/datasources/InstanceGroup.go
- pkg/datasources/KubeConfig.go
- pkg/provider/provider.go
- pkg/resources/Cluster.go
- pkg/resources/ClusterUpdater.go
- pkg/resources/InstanceGroup.go
This PR makes use of context aware functions.
> feat: use context aware functions

- docs/resources/cluster_updater.md
- pkg/api/utils/cluster_rolling_update.go
- pkg/schemas/resources/Resource_RollingUpdateOptions.generated.go
- pkg/schemas/utils/Resource_RollingUpdateOptions.generated.go
This PR adds cloud only rolling update support.
> feat: add cloud only rolling update support

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- hack/gen-tf-code/main.go
- pkg/schemas/kops/DataSource_CloudConfiguration.generated.go
- pkg/schemas/kops/Resource_CloudConfiguration.generated.go
> fix: code gen

- hack/gen-tf-code/main.go
- pkg/schemas/kops/Resource_KubeAPIServerConfig.generated.go
- pkg/schemas/kops/Resource_KubeletConfigSpec.generated.go
- pkg/schemas/zzz_utils.go
> WIP feat: add support for nullable types

- docs/resources/instance_group.md
- hack/gen-tf-code/main.go
- pkg/schemas/kops/Resource_MixedInstancesPolicySpec.generated.go
This PR fixes mixed instance policy nullable arguments.
> fix: mixed instance policy

- Makefile
- examples/aws-assume-role/cluster.tf
- examples/aws-assume-role/locals.tf
- examples/aws-profile/cluster.tf
- examples/aws-profile/locals.tf
- examples/basic/cluster.tf
- examples/basic/locals.tf
- examples/bastion/cluster.tf
- examples/bastion/locals.tf
- examples/klog/cluster.tf
- examples/klog/locals.tf
- examples/klog/provider.tf
This PR improves examples (they should be almost working as is).
> feat: improve examples

- README.md
- docs/index.md
> chore: update readme

- .github/workflows/build.yaml
> chore: update tf to 0.13.7

- .github/workflows/build.yaml
This PR adds tests with tf 0.14.11
> test: tf 0.14

- .github/workflows/build.yaml
- Makefile
This PR adds tests for terraform 1.0.1.
> test: tf 1.0

- .github/workflows/release.yaml
This PR fixes go version in release pipeline
> fix: go version in release pipeline

- docs/guides/provider.md
- pkg/api/config/Provider.go
- pkg/config/config.go
- pkg/schemas/config/Config_Provider.generated.go
- pkg/schemas/config/Config_Provider.generated_test.go
This PR adds feature flags support.
> feat: add feature flags support

- docs/resources/cluster.md
- hack/gen-tf-code/main.go
- pkg/schemas/resources/Resource_ClusterSecrets.generated.go
This PR fixes certificate perpetual diff.
> fix: certificate perpetual diff

- tests/basic/cluster.tf
- tests/external-policies/cluster.tf
This PR fixes integration tests.
> fix: integration tests

- README.md
- docs/index.md
- docs/resources/instance_group.md
- hack/gen-tf-code/docs/resource-instance-group-footer.md
> chore: doc fixes

- docs/resources/cluster.md
- hack/gen-tf-code/main.go
- pkg/api/resources/Cluster.go
- pkg/schemas/resources/Resource_Cluster.generated.go
This PR makes ssh public key optional.
> feat: make ssh public key optional

- .github/workflows/build.yaml
This PR update tf versions in ci
> chore: update ci tf versions

- docs/data-sources/kube_config.md
- examples/aws-assume-role/provider.tf
- examples/aws-profile/provider.tf
- examples/basic/provider.tf
- examples/bastion/provider.tf
- examples/klog/provider.tf
- hack/gen-tf-code/docs/data-kube-config-header.md
This PR fixes `ca_certs` docs examples.
Fixes: #500
> fix: ca_certs docs

- README.md
- docs/index.md
> fix: update readme

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- pkg/schemas/kops/DataSource_ClusterAutoscalerConfig.generated.go
- pkg/schemas/kops/DataSource_ClusterAutoscalerConfig.generated_test.go
- pkg/schemas/kops/Resource_ClusterAutoscalerConfig.generated.go
- pkg/schemas/kops/Resource_ClusterAutoscalerConfig.generated_test.go
> fix: generated code

- .github/workflows/build.yaml
- Makefile
- README.md
- docs/index.md
This PR removes old terraform tests
> chore: remove old terraform tests

- docs/resources/cluster_updater.md
- pkg/api/resources/ApplyOptions.go
- pkg/api/resources/ClusterUpdater.go
- pkg/api/utils/cluster_apply.go
- pkg/schemas/resources/Resource_ApplyOptions.generated.go
- pkg/schemas/resources/Resource_ApplyOptions.generated_test.go
This PR adds lifecycle overrides support.
Fixes #584
> feat: add lifecycle overrides support

- hack/gen-tf-code/options.go
- pkg/api/resources/Cluster.go
- pkg/api/utils/cluster_rolling_update.go
- pkg/api/utils/cluster_validate.go
- pkg/config/config.go
- pkg/schemas/zzz_utils.go
This PR fixes linter warnings.
> fix: linter warnings

- docs/data-sources/cluster.md
- docs/data-sources/instance_group.md
- docs/resources/cluster.md
- docs/resources/instance_group.md
- pkg/api/resources/Cluster.go
- pkg/api/resources/InstanceGroup.go
- pkg/resources/Cluster.go
- pkg/resources/InstanceGroup.go
- pkg/schemas/resources/DataSource_Cluster.generated.go
- pkg/schemas/resources/DataSource_Cluster.generated_test.go
- pkg/schemas/resources/DataSource_InstanceGroup.generated.go
- pkg/schemas/resources/DataSource_InstanceGroup.generated_test.go
- pkg/schemas/resources/Resource_Cluster.generated.go
- pkg/schemas/resources/Resource_Cluster.generated_test.go
- pkg/schemas/resources/Resource_InstanceGroup.generated.go
- pkg/schemas/resources/Resource_InstanceGroup.generated_test.go
This PR adds labels and annotations support.
Fixes #578
> feat: add labels and annotations support

- pkg/api/resources/InstanceGroup.go
This PR fixes instance groups well known label.
Fixes #594
> fix: instance groups well known label

- hack/gen-tf-code/main.go
- pkg/schemas/resources/Resource_Cluster.generated.go
This PR bumps cluster version to fix schema change.
> fix: bump cluster version to fix schema change

- hack/gen-tf-code/main.go
- pkg/schemas/resources/Resource_Cluster.generated.go
Signed-off-by: Charles-Edouard Brétéché <charled.breteche@gmail.com>
> fix: bump cluster version to fix schema change (#603)

- .goreleaser.yaml
- pkg/version/version.go
This PR adds a `version` package and configures `goreleaser` to set version info.
> feat: add version package

- .goreleaser.yaml
- Makefile
- README.md
- docs/index.md
- docs/resources/cluster_updater.md
- examples/aws-assume-role/cluster.tf
- examples/aws-profile/cluster.tf
- examples/basic/cluster.tf
- examples/klog/cluster.tf
- hack/gen-tf-code/docs/resource-cluster-updater-header.md
- hack/gen-tf-code/main.go
- pkg/api/resources/ClusterUpdater.go
- pkg/resources/ClusterUpdater.go
- pkg/schemas/resources/Resource_ClusterUpdater.generated.go
- pkg/schemas/resources/Resource_ClusterUpdater.generated_test.go
- pkg/schemas/zzz_utils.go
- tests/basic/cluster.tf
- tests/external-policies/cluster.tf
This PR injects provider version in updater.
> feat: inject provider version in updater

- .gitignore
> chore: improve gitignore

- hack/gen-tf-code/main.go
Signed-off-by: Charles-Edouard Brétéché <charled.breteche@gmail.com>
> chore: generator nits

- pkg/api/resources/InstanceGroup.go
This PR fixes instance groups default values.
> fix: instance groups default values

- docs/resources/instance_group.md
- hack/gen-tf-code/main.go
- pkg/schemas/resources/Resource_InstanceGroup.generated.go
Signed-off-by: Charles-Edouard Brétéché <charled.breteche@gmail.com>
> fix: set ig manager as computed

- .github/workflows/build.yaml
This PR updates rules for PR workflows.
> chore: update rules for PR workflows

- README.md
- docs/index.md
> chore: update tested CNI

- .github/cherry-pick-bot.yml
This PR preserves PR title in cherry picks PRs
> chore: preserve pr title in cherry picks prs

- hack/gen-tf-code/templates/schema.tpl
- pkg/schemas/kops/DataSource_ClusterSpec.generated.go
- pkg/schemas/kops/DataSource_ContainerdConfig.generated.go
- pkg/schemas/kops/DataSource_KubeDNSConfig.generated.go
- pkg/schemas/kops/Resource_ClusterSpec.generated.go
- pkg/schemas/kops/Resource_ContainerdConfig.generated.go
- pkg/schemas/kops/Resource_KubeDNSConfig.generated.go
> chore: sort maps by key

- pkg/schemas/zzz_utils.go
> chore: flatten duration to actual duration-value

- .github/workflows/build.yaml
This PR adds more tf versions in the test matrix.
> test: add more tf versions

- .github/workflows/verify-codegen.yaml
This PR adds a verify codegen workflow.
> chore: verify codegen

- .github/workflows/build.yaml
> chore: don't build on push

- .github/workflows/verify-codegen.yaml
This PR auto cancels verify codegen check.
> chore: auto cancel verify codegen check
